# Generated by Django 5.0.2 on 2024-04-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(choices=[("PayPal", "PayPal")], max_length=100),
        ),
    ]
